#pragma once

DWORD FASTCALL InitAutomapLayerSTUB(DWORD dwLayer);
DWORD FASTCALL GetUnitNameSTUB(DWORD Unit);
DWORD FASTCALL GetUIVarSTUB(DWORD UI);
DWORD FASTCALL TestPvpFlag_STUB(DWORD playerId1, DWORD playerId2, DWORD flagmask);
